### ISSUE TITLE
fix all the quiz due dates

### ISSUE THREAD

**Issue by elliewix** [elliewix/IS-452-Fall2018#34]

**Comment by nicklalone** [comment]
These should be Sunday at 1155pm or Monday by 5pm?


Nick LaLone
iSchool
University of Illinois at Urbana Champaign
www.nicklalone.com

**Comment by elliewix** [comment]
Sunday night.  This is done.

I'm open to monday afternoon if you think that's better, but we can discuss and see how it goes.

**Comment by elliewix** [comment]
Closing now.
